hash-format = "sha256"

[[files]]
file = "README.md"
hash = "ba5ef66b753f9bc58f5dc8a8d03c69aa7d7ce937733abc55c2177ad5d0c4beb6"

[[files]]
file = "mods/almanac.pw.toml"
hash = "cfc918961faa30220a1c4d113d7ffec45ac4225c72ed7de63aa5f32210d04c4f"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "a7046e95eeea765e502fb586d11ea0c2c0ed9d2df85a23201d5c830ee446a767"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "58134b8f4cca95555746efad25cc8a56c39ed57ba05f78d3aa61b603d378180c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c842647bf2f4cc2bbe7d1f1b14ee866437cdecf42aacb07dacc3a11501ccd8d6"
metafile = true

[[files]]
file = "mods/areas.pw.toml"
hash = "be6dfd7655e5b692b41e67a11c1663226608f89c6cb9a00377a615fd63ecf9d3"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "80dc11949c216c05d70a77dbddc1dae6e993b35da3819ff3b06e8a39d7e38837"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "919e29749dc879ded6ac020cee1b0b3076398df16b151840c13afafe89e160b0"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "298f25096587fbe2570f15755d306a9f0ac11ba70e31214f139f63510904680f"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "fe7cc93d29b35aa2e504bd4dd8574897b23ca61a56eaab49bfdea24d38699396"
metafile = true

[[files]]
file = "mods/blanket.pw.toml"
hash = "204a6e607eabf19083f9a4f99e7bc33ff9df95d8c77deaba58f67a6a19f8c811"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "2b5efcc87c42fbd4cb2732494b5767e9f393fe7f7c4f1dd2620ef633e86ddd2b"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c1c0a579143f67484eab48fffc1412db4cd9085dd72b418551a7ea8ca4525ca7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cfc2c53b0d3cee953b423fe9abf210d87281d5bf774dab20cf03abe6224a9883"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "563b5211676d155e7f3901f63e62e9fcc4a790ec4a224e71461e2910397dee53"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c994836d4261db437bf7cfc92f7427abb0c115fcc6aa4d01dd3878a4f650e7b9"
metafile = true

[[files]]
file = "mods/combat-roll.pw.toml"
hash = "22fecc113e82f1130ef7fe91b63ff379671bacf1440813935a35e494c6021113"
metafile = true

[[files]]
file = "mods/conduits-prevent-drowned.pw.toml"
hash = "ded731a21a515b3b113b2dabaa56537ebff1407eafc8a5df632c760e1cfb0ec8"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "0f06ba5b409ad41ccb7c2356b1407fe751bf3794386d8ddca924475f74c50822"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
hash = "04ee1dd35f56bc8dd1ca389b9a4ed712dba4b253e83e9549364f2e365ce38bed"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "fc2bac2b210deac64f82dca96d85c8cb575815e75070bd7f3563c559f1ebe14a"
metafile = true

[[files]]
file = "mods/dismount-entity.pw.toml"
hash = "3bcbe067758c8fae144e875813067e3147452dac6843bb0f1657d19b8c175384"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "4b1d22d47cd63e76528586d045ce2135da425af83aaeca18377a911ba7ed0daa"
metafile = true

[[files]]
file = "mods/dragon-drops-elytra.pw.toml"
hash = "485fe9c7220a296ebc1b399bbe15b9f4cbfff9a643f62a13daf95333866a79c0"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d29e52714402fe3f95bc68b8b060da85cda3e575247cdc6f7d00c2fcfe270838"
metafile = true

[[files]]
file = "mods/easy-elytra-takeoff.pw.toml"
hash = "6e5fffff0f6c48dd6aca27938e6a9c34d0b22f653481d3971675423ae3fb4d5c"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "9099b858e94f6f81db890c7d46f85601dee71ba33fb7ae19773b8da2ce8c3834"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "bd02cc1b0ee4feea5c920bc2b3858ddb3c3d98ece259507169956fdabb54b759"
metafile = true

[[files]]
file = "mods/edibles.pw.toml"
hash = "322b631cbdc15c4e10064820272599c2fcb4fe4d6a94a20631f1119ec6057761"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "767557b88c430fbf901adfc6870f61166e9b73fcb8d76110fdab1fcb2fab6eba"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "a8800671ba62afc0a0a2bcbf4330ba7a5906f5fba7ec88b6d5afac2572ecd617"
metafile = true

[[files]]
file = "mods/faster-crouching.pw.toml"
hash = "8d794e19c43f4bcc4ac026dead2068c3ca31d1144067fe0824f53dd30cdea063"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "d5d726aacfb80dbe7cc8da290ea3d9557d4fcb5dfa2078d69ac276cdeff485b2"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "d267496fd8d34872acfa37070b73b6c048f361293e4d71af69bc292cd3b30b55"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "7f00e8c31c1249e984d34158e0d33c1e8c31dcd7977d4e4e3d90852ad20221ae"
metafile = true

[[files]]
file = "mods/healing-campfire.pw.toml"
hash = "b825c52920102ccdca07f330e53bb135518fe422c238ab3d38feb90a764ae068"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b6f9dd6b376f4aee11cc58dda69d507f7b1b7e15181584875013ab3e5f761cd0"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "0adcdcc6092f8709a396ef315823c6a5db0bb3b35307d7f1c16f3e932c93b079"
metafile = true

[[files]]
file = "mods/inventory-mending.pw.toml"
hash = "b06e4d737edfd836d33e9e5a7ebb3c13ba5539a36cf879e51a2d1d4b87c94994"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "b156d0622549a72f9759637f378594237359a16de7c69cbac953a84cd3108662"
metafile = true

[[files]]
file = "mods/inventory-totem.pw.toml"
hash = "c4457593a98c59266c76be17e5683dd672e53dde40a7969ba6821a935c5604cd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "012ec092803f672ce6f884dfa400497e2e4e8063a3af4e3cdee911dea10ab2c9"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "f010fbe1c0b279af7aceb554e071b8ee05a43214e6b21fb346b5a17db824cfb0"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f012982b9554a3d11943919397a7c296f177dfada699f9e25179b4991d41982c"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "928bee3054db625cd156c4aa5607a98f1b54fe8ab82d1c486f1f5c54f016a979"
metafile = true

[[files]]
file = "mods/keep-my-soil-tilled.pw.toml"
hash = "1b5dace27fcc3b60445e62740c066e65b217d00c51d37fe2cff64f6f08715f8d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "cde0e515451bd0390bde963249010aa077aa61c4671e087cdb2e0809131f6aca"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d92304640cdb4452147f87990faaeaf18d6aced410990400f3ec636752825ac6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "65e636524c7311fe98f308e26a2b67ed2589957aab04313e541c75afd701284a"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "b873c64235d94065526169aeb2157087b738f0aa483feae75c5a0b42610ed8d0"
metafile = true

[[files]]
file = "mods/lovely_snails.pw.toml"
hash = "a5137dcf2b747512f4bb13c6247f3cb91bc337cf1ff434679178bf97013a5748"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "0a4bd44ed6052939a41a5e4b9578148ceb72312730286fe0580031b08e487d6b"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "ebb68af5236a220b684bc8630917dd88987da7d31e8ae8d2b3bf0865a43a3d7e"
metafile = true

[[files]]
file = "mods/mineral-chance.pw.toml"
hash = "ac1efaa91811646ba521a2529f0690ea89ddab901182eee98be95bc793257723"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "ebbaf07d4e04f172081d5f4bec47837ae1008c5a6dbedc32f7ba471dd3d004cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "87f32c96066eb295c234effb49f6f5cbd5956316a3a750a3989cfb645b3fd397"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "89c1f8a8067f8b844a6c965e382e14c68e306510b949aee00772e3e2773956ec"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6e7bf134fe18e3073df2d46b44ab636fc9c76d1227478c251eacdafaa69d3fd6"
metafile = true

[[files]]
file = "mods/name-tag-tweaks.pw.toml"
hash = "5141e7bd9e5882a30eb4c93147a5a9c47da07e35012a4167183678ad9499a383"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "ba2eb4a9003acff3b9280612d228466ba749d6d7329605ad748401f686c78c73"
metafile = true

[[files]]
file = "mods/no-hostiles-around-campfire.pw.toml"
hash = "f5453da0bf606d87308e312fecc5d1fa8b9def3decd7ecce2a456cf8a8149ee9"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "da9773fa4a8909df91f5d928de78434aa110dc1fc922d9f7f9532e87270f6cc9"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "89e1024a3ec6d23c0f7111995ed0cb72f6b3c209edd133daa40c4e5c53f37148"
metafile = true

[[files]]
file = "mods/passive-shield.pw.toml"
hash = "f313651fc543b769d302e5bbe7a8ba44b53239df9651f4936fae016b0a2bd6bb"
metafile = true

[[files]]
file = "mods/piglin-names.pw.toml"
hash = "391c77e94787a3bbd604f5972cd30496731e61ec2e730de1f4005f6726efd205"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "58f3d7d8e37296c66c15706e332b080f451f7f8e84cc5c7617e156290b16f544"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
hash = "f9400b5d69436f1439463e761922eff413249d9d29d23228f2c9389cff9058e0"
metafile = true

[[files]]
file = "mods/respawning-shulkers.pw.toml"
hash = "7c77bbf4995a070e06cd2da0e171034edddf150d41d3d62065b12b75f11d7c3c"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "38fed02cac9c05058028e5f2f64d57d3984fe422f76b5dfb2162ffeaf61f7a73"
metafile = true

[[files]]
file = "mods/shulker-drops-two.pw.toml"
hash = "9771829155b7905b687d3b4228b832cbcc7c01a06c0ba773c36d285515b1e206"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "07195a6fc83d0e6645c7b16ccbde422168363a75833ce999c557f490d8e691da"
metafile = true

[[files]]
file = "mods/silkier-touch.pw.toml"
hash = "28b911115deef2a474d7fa739d13c49176aa467cb3b50ed0855bfb2dd3e7d351"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b99aff4f159bf39bd866cbb632b40f495047ffb4d379b08cc8e5ead37b83fb67"
metafile = true

[[files]]
file = "mods/smaller-nether-portals.pw.toml"
hash = "fd6396e6c37d58325dab04a9b466902f7a74b8eb69d24e57e87da41e006138e9"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "fa41e05d17ae825fe60001763b2160c15b3998fb0352fce0e70af67172afb262"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d6e22a99e0b73a91cfd528aed964bc8acb001188e76804406b998a19f645fbe1"
metafile = true

[[files]]
file = "mods/spiders-produce-webs.pw.toml"
hash = "134724c02129914ae4a9148bea0b629e027348af38f627e541a3bec23cc68a99"
metafile = true

[[files]]
file = "mods/stack-refill.pw.toml"
hash = "528f7f5b4614a80038858dc8e5dc9d0f1d809d50b2aa9bb73d0e88e630722eb6"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "66ec69b7956bd72b72962e00f2a254987d40624cf9c94f750662da51d824464a"
metafile = true

[[files]]
file = "mods/tnt-breaks-bedrock.pw.toml"
hash = "4372dda2d2cf3df3d8a9d4129cbe31d5115d3a7ddaba58b593b20675cd87e89b"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "7664a75770769643b9f29f24301a787a23c549432a8dea2153b903896f777d50"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "fde32c6651f8900fc5d8466af4af3b30d557dce41ef413c5eeba3d89672b40e8"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "b1d493b001787b4074512b6d1e2ea36854b634d8d571843d4cfccdd69ae8d188"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "2401c3c5f4a94e87bc86be4ffa0d3e679510dd918cb14b3ca577683491d3df5c"
metafile = true

[[files]]
file = "mods/underground-beacons.pw.toml"
hash = "9ce3f4c97b3d3da1e322a5fcc3fddaff6bc3d796fd8d77781b5dfe7f26b031ac"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "6a75204bd64880265c95a8d3f2881965f05504509523605e0e22aba96adaa511"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "71442b40708a31755700aacd3d0a8fdd3e8c241ec46a77c5c9ff0b465a4dcf9a"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "0dd3e32f9f7b51eb12a531806361179870b9604f645924ded5e27f2a4010bac8"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "c9855f4143953afa24c13886f1137c76cd291bcf536d60e5ea8e0769bd5064e3"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "581f3daa04321365c253422568a5e839d6e9788d868f887cfbb06698d6868984"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "c9652825f9cb65d2accfc03696868fc7c44e83f6bf03f62c39c3feaef3a59de1"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "8d07ebd7f77afe0fc10be6c9ecb57cfe70b2e4810df9e5dd2a1a850c4a456006"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "5738956a3ecad28a7013bf3841c376cd74d05140a01d663b1cb867fc748d1e14"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "93e9738a9a318cfca75bc6e7fed90072ff44f37d1704ff337dc4b30f18be4156"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "54a23d6b456034d679937e90ee5f29607c3cbc1a223b51eba49e003dda82cdfd"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "b5a6560081f3e92d55d370364df5cdb8ecdd50f83c3b6187d74d22834de78d12"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "8c47d6b560cb98f9b70df290fb0934123f00730ec8b02e3b682bebfa73afc5b7"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "7f0def80e684d38426a2edad78f82cdaf6035513f6f8e5ce851b0451c7f9772c"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "1a4c115ce16216cb6f8458f5c72dfee5657cb990847b3afb7f28e2ed2f41ef91"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "657ead40dd2f3ab96810e34d31a35b858bee03a585319ba975320bb8676c312d"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "79643230c997a50c619c844c24aa931d0f2c08b26a953b5c9364d224240dd94b"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "c97d15447c8ba815d516a4e7c4815b885273bf074e0d9ab7fe2106293e3bc689"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "ca979c2dfe63824909c33c5c7e9d767e563a46498fa141882c4fcc7d4c7e1381"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "28db6edf7cf7a5e7c70c5fd1619705983b1e904f3b96423d633cd50a446a5722"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
hash = "c0fffd2fb01d6ee0d474ce95f178ac4dbb9cc0ce2cccf0085d17598802774b7d"
metafile = true

[[files]]
file = "mods/zombie-awareness.pw.toml"
hash = "43492c7f91bbfceaeed4d97e689e0a80c4cadeff3ffdc5693b9cfcfb11147b40"
metafile = true
