hash-format = "sha256"

[[files]]
file = "README.md"
hash = "d763c0858ea5f49717e051f52bf0d1288621bf279cccc17e8e3e3a730edbc623"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8f4c5df67ca83417b3ed21ce3ae411447a612302519cf6077996c34f50442a35"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1c294ece0bf6b92233d911b5bcd3ab6b0a9cd1920f23c64b4dbc00b8a83a1393"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "4d327db95d15a81aa38ca20bcdfd573a0537360c898622d13b263b2d9c06cd8d"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "e171a4219a5fce5dedd042ebe9b9a8357788f67bbd23569e072b07ac66cefaee"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "0d232248a360de3994b639d6bd3430806e6d3434c89bd7a44a33636e8b401aa7"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "ffbe86f7b3e1108d5abae3d1a53a7d1ea62dc5a4ec83ed440781ddec228139a3"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "4d98bdba90cdeae788a747bb6fe7d438ba49fdc4eb67c38d4573304eec4a2ef8"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "57c6e291ce10527ca8672b0ab508dea77afa067b7ec5daf772904cf2105e5e1e"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "30c81f667b06ad090542f51753645ca8541908c225cc0d9106f725560eb51914"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "ffcf32caf3dda8f05adb109dc86c477cf1bb768bac6232bc5bcf0d60a7861bcb"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "a9f7ce3ef90cd500e451ff6534d42f0532150d5f207c974468295fbe8c7b5a47"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "9ebe3f899af40f9bec87d76c2c3dc85004278d30165fcbc0020a11d47da5d35e"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "eccab4f9bcbc604767e9794ca746588f673db63f85bd63adf0b505b396a3c23c"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "a33c822c6525c8b708475161e263cb18883332383a6b25e2b5915623f0e5b85c"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "15ef858f138af87eb7376988107cb6f61bccf578c4c8bcca44a473a0ca128e41"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "66e4fca8e34915da64ec530a9153500271016e2086752a7f196f71a5c6135d84"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "1bd0ba1128e6ae3f926298c2ffe33180cca75362fae3bd92146d43977297f01c"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "f0779c5ec85b19542d39dd3df11c0fd521c465f5da2bafc9d1a6250a30719cc6"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "57ae99f727e3fcd7a1abbc624bf14cafa5f092f2082dcf3edc609289efb25c15"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "b7152fd543e5efd1233dfc49ddb690332d98bdb986b4b7a289565fbf3af6cbe5"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
hash = "486344643491c3745e4ccef40d98f987f4448345be36c34827b3b62ce8d2dd7e"
metafile = true
