name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b325060393c08ba110917c01ed86bb592a7834edd63d2bf18145ba01e3c5b73a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
