name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "341ff5048b17dae2d009bd4a5e8ec9d132320f69a2a2951472a77fa621a02f9d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
