name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65d5633dea8d4a670567909267ab2351d306ae788af41c99a392abb035368048"

[versions]
fabric = "0.16.9"
minecraft = "1.21"
