name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "006837a4b7b7ebc0f63071018bf8c7bb376e36d1bca1f5a2ffe1217bc2d5346a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"

[options]
acceptable-game-versions = ["1.21.x"]
