name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5a9fe90f8dcd34b21aa6e68e2e4c75e6cac9b8148bc3edae6d481beeec6fe6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.x"]
